"""
Expected PostgreSQL reference rows for the small TPC-H fixture and comparison
helpers for YDB integration tests.

Oracle source: PostgreSQL 15 with create_postgres.sql / insert_postgres.sql.
Generated by running queries_postgres.sql against the fixture dataset.

None means the query has a known transpilation bug and is marked xfail.

Known xfails and their root causes:
  Q02 — correlated scalar subquery: decorrelate() loses outer-table reference
          after unnesting (same table names in inner and outer scope confuse scope
          resolution, causing the outer p_partkey column to be detached).
  Q04 — EXISTS subquery: not yet supported in decorrelate().
  Q11 — HAVING scalar subquery: decorrelate() incorrectly treats the non-correlated
          inner subquery as correlated because inner/outer queries share the same
          table names without aliases; incorrect GROUP BY is injected.
  Q13 — LEFT OUTER JOIN ON with unqualified columns: YDB requires table-qualified
          columns in JOIN ON clauses ("correlation name"), but the original SQL has
          none and schema info is needed to add them automatically.
  Q16 — COUNT(DISTINCT col) in JOIN query: YDB requires table-qualified columns
          in DISTINCT aggregates when there are JOINs.
  Q17 — correlated scalar subquery (0.2 * avg(l_quantity)) whose result column is
          auto-named "0.5" by the optimizer, breaking the HAVING reference.
  Q18 — l_orderkey is ambiguous after unnesting the IN subquery (appears in both
          the outer lineitem table and the unnested _u_0 alias).
  Q20 — same 0.5 * SUM() column-naming issue as Q17.
  Q21 — EXISTS / NOT EXISTS subqueries: not yet fully supported.
  Q22 — NOT EXISTS subquery: not yet supported.
"""

from __future__ import annotations

import datetime
import math
from typing import Any, Sequence

# fmt: off
TPCH_EXPECTED: list[list[list[object]] | None] = [
    # Q01 — aggregate per (returnflag, linestatus), ordered
    [
        ['N', 'F', 71.0, 9550.0, 8976.5,  9121.53, 14.2, 1910.0, 0.056, 5],
        ['N', 'O', 36.0, 3550.0, 3342.5,  3409.35,  7.2,  710.0, 0.056, 5],
        ['R', 'F', 20.0, 2400.0, 2280.0,  2325.6,  20.0, 2400.0, 0.05,  1],
    ],
    # Q02 — best supplier for BRASS part in EUROPE
    [
        [1500.0, 'Supplier#000000001', 'GERMANY', 2, 'Manufacturer#2',
         'N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ', '17-891-367-3479',
         'each slyly above the careful'],
    ],
    # Q03 — unshipped orders with highest value
    [
        [4, 744.0, '1995-01-15', 0],
    ],
    # Q04 — order priority counting (EXISTS subquery — known transpilation bug)
    None,
    # Q05 — revenue by nation in ASIA region (1994)
    [
        ['JAPAN', 564.0],
    ],
    # Q06 — forecasting revenue change (single aggregate)
    [
        [120.0],
    ],
    # Q07 — volume shipping between FRANCE and GERMANY
    [
        ['FRANCE', 'GERMANY', 1996.0, 1128.0],
    ],
    # Q08 — national market share (BRAZIL in AMERICA, 1995-1996)
    [
        [1995.0, 0.0],
    ],
    # Q09 — product type profit measure by nation and year
    [
        ['FRANCE',  1996.0, -312.0],
        ['FRANCE',  1994.0, -130.0],
        ['GERMANY', 1995.0, -106.0],
    ],
    # Q10 — returned item reporting
    [
        [1, 'Customer#000000001', 2280.0, 5000.0, 'FRANCE',
         'IVhzIApeRb ot,c,E', '13-812-177-8836',
         'ctions. accounts sleep furiously even requests. regular, regular accounts'],
    ],
    # Q11 — important stock identification (GERMANY suppliers, threshold 0.0001)
    [
        [1, 100000.0],
        [5,  66000.0],
        [2,  30000.0],
    ],
    # Q12 — shipping modes and order priority
    [
        ['MAIL', 0, 1],
        ['SHIP', 1, 0],
    ],
    # Q13 — customer distribution by order count
    [
        [2, 3],
        [1, 1],
        [0, 1],
    ],
    # Q14 — promotion effect (single aggregate)
    [
        [100.0],
    ],
    # Q15 — top supplier (CTE)
    [
        [2, 'Supplier#000000002', '89eJ5ksX3ImxJQBvxObC,',
         '33-206-147-3644', 1128.0],
    ],
    # Q16 — parts/supplier relationships
    [
        ['Brand#23', 'ECONOMY ANODIZED STEEL', 3, 3],
        ['Brand#11', 'ECONOMY BURNISHED COPPER', 49, 2],
        ['Brand#34', 'LARGE ANODIZED STEEL', 23, 1],
    ],
    # Q17 — average yearly revenue (correlated subquery — known transpilation bug)
    None,
    # Q18 — large volume customer (none in fixture, sum(l_quantity) > 300)
    [],
    # Q19 — discounted revenue (multi-condition OR)
    [
        [3360.5],
    ],
    # Q20 — potential part promotion (CANADA suppliers with forest% parts)
    [
        ['Supplier#000000003', 'q1,G3Pj6OjIuUYfUoH18BFTKP5e'],
    ],
    # Q21 — suppliers who kept orders waiting (EXISTS/NOT EXISTS — known bug)
    None,
    # Q22 — global sales opportunity (NOT EXISTS subquery — known transpilation bug)
    None,
]
# fmt: on

assert len(TPCH_EXPECTED) == 22


def _normalize_cell(v: Any) -> Any:
    if v is None:
        return None
    if isinstance(v, datetime.datetime):
        return v.replace(tzinfo=None).date().isoformat()
    if isinstance(v, datetime.date):
        return v.isoformat()
    if isinstance(v, bytes):
        return v.decode("utf-8")
    if isinstance(v, float):
        return v
    if isinstance(v, int):
        return float(v)
    return str(v)


def _materialize_ydb_row(row: Any) -> tuple[Any, ...]:
    if hasattr(row, "__len__") and not isinstance(row, (str, bytes)):
        return tuple(_normalize_cell(row[i]) for i in range(len(row)))
    raise TypeError(f"unexpected row type: {type(row)}")


def _row_almost_equal(a: Sequence[Any], b: Sequence[Any]) -> bool:
    if len(a) != len(b):
        return False
    for x, y in zip(a, b):
        if x == y:
            continue
        try:
            if math.isclose(float(x), float(y), rel_tol=1e-4, abs_tol=1e-6):
                continue
        except (TypeError, ValueError):
            pass
        if str(x) == str(y):
            continue
        return False
    return True


def _multiset_equal(expected: list[list[Any]], actual_rows: Sequence[Any]) -> None:
    act = [_materialize_ydb_row(r) for r in actual_rows]
    exp = [tuple(_normalize_cell(c) for c in row) for row in expected]
    if len(exp) != len(act):
        raise AssertionError(
            f"row count: expected {len(exp)}, got {len(act)}\n"
            f"  expected: {exp[:5]}\n"
            f"  actual:   {act[:5]}"
        )
    used = [False] * len(act)
    for er in exp:
        found = False
        for j, ar in enumerate(act):
            if used[j]:
                continue
            if _row_almost_equal(er, ar):
                used[j] = True
                found = True
                break
        if not found:
            raise AssertionError(
                f"no matching row for expected {er!r}\n  actual: {act!r}"
            )


def assert_matches_postgres(
    result_sets: Sequence[Any],
    expected: list[list[Any]] | None,
    *,
    query_label: str,
) -> None:
    """Assert that YDB result matches the PostgreSQL oracle."""
    if expected is None:
        raise AssertionError(f"{query_label}: expected is None (xfail not applied?)")
    if result_sets is None or len(result_sets) == 0:
        raise AssertionError(f"{query_label}: empty result from YDB")
    rows = result_sets[0].rows
    if len(expected) == 0:
        assert len(rows) == 0, (
            f"{query_label}: expected 0 rows, got {len(rows)}: {list(rows)[:3]}"
        )
        return
    _multiset_equal(expected, rows)
